"""This module provides the functions to calculate and filter the derived traits.

Functions:
    calcu_derived_trait: Calculate the derived trait values.
    filter_invalid: Rule out the invalid traits.
    filter_colinearity: Reduce the traits that are highly correlated.
"""
from typing import NewType

import pandas as pd

from glytrait.formula import TraitFormula
from glytrait.load_data import AbundanceTable
from glytrait.meta_property import MetaPropertyTable


DerivedTraitTable = NewType("DerivedTraitTable", pd.DataFrame)


def calcu_derived_trait(
    abund_df: AbundanceTable,
    meta_prop_df: MetaPropertyTable,
    formulas: list[TraitFormula],
) -> DerivedTraitTable:
    """Calculate the derived trait values.

    Args:
        abund_df (AbundanceTable): The abundance table, with samples as index and Compositions
            as columns.
        meta_prop_df (MetaPropertyTable): The table of meta properties generated by
            `build_meta_property_table`.
        formulas (list[TraitFormula]): The trait formulas.

    Returns:
        DerivedTraitTable: The trait values, with samples as index and trait names as columns.
    """
    # The meta-property table the formulas use for initialization must have
    # the same order of index as the abundance table's columns (glycans).
    # `TraitFormula.calcu_trait` will raise an assertion error if the orders
    # of the glycans are different.
    # # (See `TraitFormula`)
    meta_prop_df_ordered = meta_prop_df.reindex(abund_df.columns)
    trait_series: list[pd.Series] = []
    for formula in formulas:
        formula.initialize(meta_prop_df_ordered)
        trait_s = pd.Series(
            data=formula.calcu_trait(abund_df),
            index=abund_df.index,
            name=formula.name,
            dtype=float,
        )
        trait_series.append(trait_s)
    derived_trait_df = pd.concat(trait_series, axis=1)
    derived_trait_df = derived_trait_df.round(6)
    return DerivedTraitTable(derived_trait_df)
